"""initial schema

Revision ID: 94124595f4f1
Revises: 
Create Date: 2026-07-31 15:21:20.790853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94124595f4f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('requirement_analysis', 'test_generation', 'reviewer', 'consensus', 'coverage', 'quality', name='pipelinestage'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_templates_stage'), ['stage'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_owner_id'), ['owner_id'], unique=False)

    op.create_table('experiment_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('reviewer_enabled', sa.Boolean(), nullable=False),
    sa.Column('consensus_enabled', sa.Boolean(), nullable=False),
    sa.Column('coverage_enabled', sa.Boolean(), nullable=False),
    sa.Column('quality_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_debate_rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_configs_owner_id'), ['owner_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('config_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('single_llm', 'multi_agent', name='experimentmode'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['experiment_configs.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_owner_id'), ['owner_id'], unique=False)

    op.create_table('user_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_stories_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_stories_project_id'), ['project_id'], unique=False)

    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_story_id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.Enum('single_llm', 'multi_agent', name='experimentmode'), nullable=False),
    sa.Column('current_stage', sa.Enum('requirement_analysis', 'test_generation', 'reviewer', 'consensus', 'coverage', 'quality', name='pipelinestage'), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['parent_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['user_story_id'], ['user_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipeline_runs_user_story_id'), ['user_story_id'], unique=False)

    op.create_table('acceptance_criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acceptance_criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acceptance_criteria_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('agent_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('requirement_analysis', 'test_generation', 'reviewer', 'consensus', 'coverage', 'quality', name='pipelinestage'), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('raw_input', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_template_id', sa.Integer(), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('success', 'failed', name='executionstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_executions_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('experiment_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiment_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_metrics_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_metrics_metric_name'), ['metric_name'], unique=False)

    op.create_table('export_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('test_case_version_ids', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('export_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_logs_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('requirement_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('actors', sa.JSON(), nullable=True),
    sa.Column('preconditions', sa.JSON(), nullable=True),
    sa.Column('main_flow', sa.JSON(), nullable=True),
    sa.Column('alt_flows', sa.JSON(), nullable=True),
    sa.Column('ambiguities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('requirement_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_analyses_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('coverage_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('acceptance_criterion_id', sa.Integer(), nullable=False),
    sa.Column('covered', sa.Boolean(), nullable=False),
    sa.Column('covering_test_case_ids', sa.JSON(), nullable=True),
    sa.Column('gap_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['acceptance_criterion_id'], ['acceptance_criteria.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coverage_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coverage_reports_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_test_case_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('traces_to', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.Enum('generator', 'consensus', 'manual', name='generatedby'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'reviewer_flagged', 'consensus_resolved', 'manual_approved', 'rejected', name='testcasestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['traces_to'], ['acceptance_criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_test_cases_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('debate_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.Enum('reviewer', 'generator', 'consensus', name='debatespeaker'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debate_turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_debate_turns_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    op.create_table('manual_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('approve', 'edit', 'reject', name='manualaction'), nullable=False),
    sa.Column('edited_content', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('manual_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manual_reviews_test_case_id'), ['test_case_id'], unique=False)

    op.create_table('quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('atomicity_score', sa.Float(), nullable=True),
    sa.Column('traceability_score', sa.Float(), nullable=True),
    sa.Column('duplicate_flag', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_reports_pipeline_run_id'), ['pipeline_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_reports_pipeline_run_id'))

    op.drop_table('quality_reports')
    with op.batch_alter_table('manual_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manual_reviews_test_case_id'))

    op.drop_table('manual_reviews')
    with op.batch_alter_table('debate_turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_debate_turns_pipeline_run_id'))

    op.drop_table('debate_turns')
    with op.batch_alter_table('test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_cases_pipeline_run_id'))

    op.drop_table('test_cases')
    with op.batch_alter_table('coverage_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coverage_reports_pipeline_run_id'))

    op.drop_table('coverage_reports')
    with op.batch_alter_table('requirement_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_analyses_pipeline_run_id'))

    op.drop_table('requirement_analyses')
    with op.batch_alter_table('export_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_logs_pipeline_run_id'))

    op.drop_table('export_logs')
    with op.batch_alter_table('experiment_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_metrics_metric_name'))
        batch_op.drop_index(batch_op.f('ix_experiment_metrics_experiment_id'))

    op.drop_table('experiment_metrics')
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_executions_pipeline_run_id'))

    op.drop_table('agent_executions')
    with op.batch_alter_table('acceptance_criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acceptance_criteria_pipeline_run_id'))

    op.drop_table('acceptance_criteria')
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_user_story_id'))
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_experiment_id'))

    op.drop_table('pipeline_runs')
    with op.batch_alter_table('user_stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stories_project_id'))
        batch_op.drop_index(batch_op.f('ix_user_stories_dataset_id'))

    op.drop_table('user_stories')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_owner_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))

    op.drop_table('projects')
    with op.batch_alter_table('experiment_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_configs_owner_id'))

    op.drop_table('experiment_configs')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_owner_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('prompt_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_templates_stage'))

    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
